### ISSUE TITLE
Оформление плагина в виде модуля для postss

### ISSUE THREAD

**Issue by 4ok** [bem-incubator/bem-grid#111]
Почему модуль не оформлен в виде плагина для postcss, а используется так https://github.com/bem-incubator/bem-grid/blob/master/.enb/make.js#L34-L47?

**Comment by awinogradov** [comment]
Да в общем-то не почему. Просто так было удобно. Отформатировать вполне можно. Кроме-то такое гарантирует работу с любым препроцессором, а не только с postcss.

**Comment by 4ok** [comment]
Не нравится то, что при сборке запускается еще одна сборка, сначала показалось, что проблема у меня в проекте, потом понял что сборка идет в enb-bem-grid. Плюс появилась проблема с кэшем, при такой двойной сборке, пока не разобрался из-за чего конкретно, копаю
