### ISSUE TITLE
move row_flexbox_detect to ua__flexbox

### ISSUE THREAD

**Issue by ilyar** [bem-incubator/bem-grid#82]
Библиотеке надо знать о поддержке фичи, она могла бы реализовывать `ua__flexbox` и зависит от него, а это позволяет зависимым от библиотеки проектам использовать механизм ua. Это позволит библиотекам работать в единых терминах.

**Comment by voischev** [comment]
@ilyar Кайф!

**Comment by zxqfox** [comment]
Имхо, ua можно было бы унести в bem-modernizr ;-) Чтобы не реализовывать по кускам в разных библиотеках ;)

**Comment by verybigman** [comment]
@zxqfox это все уровни) Больше больше уровней. Одна либа это слишком просто)

**Comment by zxqfox** [comment]
Да просто пора делать свой bower) со знанием о технологиях, уровнях и блоках

**Comment by verybigman** [comment]
Может просто bower научить) Заодно там и неймспейсы порешать)

**Comment by ilyar** [comment]
Имхо, надо решать в текущих условиях и отдельно обсудить на форуме, как это может быть сделано иначе.

@zxqfox если и выносить я за `bem-ua`.
@verybigman интересно понять подробности твоей идеи, раскрой пожалуйста или дай ссылку или это уже обсуждалось.

**Comment by ilyar** [comment]
> @zxqfox Да просто пора делать свой bower) со знанием о технологиях, уровнях и блоках
> @verybigman Может просто bower научить) 

 Может быть `npm`? Есть интересный тренд отказаться от `bower`, пример: [Welcome, jQuery developers!](http://blog.npmjs.org/post/111385956875/welcome-jquery-developers). Тоже интересно узнать подробности из чертогов разума.

**Comment by zxqfox** [comment]
@ilyar я против бездумного следования трендам. bower устанавливает зависимости плоским списком, npm в процессе активного рефакторинга. Перепубликовать пакеты можно в любой момент, когда будет готов базовый функционал. Worth it?

**Comment by tadatuta** [comment]
я продолжаю наивно верить, что еще чуть-чуть и смысла в всяких модернайзер-лайк штуках станет сильно меньше, потому что как только умрут IE 8 и опера 12, останутся только автообновляемые браузеры.
но так как мы уже сейчас для IE 8 [собираем отдельный CSS](https://ru.bem.info/libs/bem-components/v2.1.0/#Поддержка-ie8), а опера 12 более-менее все умеет, то какую-то дополнительную движуху я бы тут не разводил.

**Comment by zxqfox** [comment]
@tadatuta мы всегда сможем перестать использовать библиотеку, а вот с вырезанием кода блока из репозотория — сложнее. не сильно, но все же это сложнее, чем перестать использовать библиотеку. Почему ты против? Все равно, если они все удачно помрут, надо будет вырезать этот код?

**Comment by tadatuta** [comment]
@zxqfox я не принципиально против, я скорее считаю, что оно того не стоит.

вот взять конкретный пример про flexbox из данного issue. он поддерживается всеми, кроме IE 8.
если мы считаем, что все-таки пока хотим поддерживать IE 8 и при этом используем `bem-components`, то логично костыли для восьмерки консистентно класть в `ie.css` вместо того, чтобы начать мейнтейнить +1 библиотеку со всеми ее апдейтами-депендов-написанием-ридми-подключением-на-проекты-вот-это-вот-все накладными расходами.

**Comment by zxqfox** [comment]
@tadatuta Тезисно :)

- эта библиотека вся на flexbox, она не должна как-то влиять на остальные, которые поддерживают или нет ие8, для ие можно фиксировать ширину экрана и сделать на js все, что невозможно стандартными средствами — библиотек много, не все они флексбокс и ие8-инкомпатибле;
- в идеальном мире, к которому мы идем, цена мейнтейна библиотеки должна быть близкой к нулю — т.е. шатать блоки туда суда (в т.ч. между библиотеками) должно быть так же просто, как и публиковать в npm и bower или пушить в ветку в гите;
- про апдейто-депенды — это очень горячая тема, которую хочется начать обсуждать прямо год назад, и в процессе обсуждения принять какое-то соглашение по размещению библиотек, мета-информации в них, и т.д. вопрос затяжной, и чем раньше начнется процесс — тем лучше, имхо, но чем больше у нас будет таких мелких библиотек — тем проще будет с созданием новых (т.е. цена будет все падать и падать), значит дорога верная ;-).

:fire:

**Comment by tadatuta** [comment]
@zxqfox ну ощим, если кто-то запилит такую библиотеку и будет ее поддерживать, то я даже не против того, чтобы положить ее в инкубатор ;)

**Comment by zxqfox** [comment]
@tadatuta Так все равно же вырезать ua из bem-core...

**Comment by verybigman** [comment]
Развели флуд на пустом месте)))

**Comment by verybigman** [comment]
Будет сделана нормальная поддержка ie, скорее всего через lost
