### ISSUE TITLE
Почему реализованно именно так?

### ISSUE THREAD

**Issue by 4ok** [bem-incubator/bem-grid#84]
Объясни, почему сделанно именно так:

```css
@media $medium {
    col_base_classes(m);
}

@media $medium_only {
    col_visibility_classes(m);
    col_order_classes(m);
}
```

, а не так:

```css
@media $medium {
    col_base_classes(m);
    col_visibility_classes(m);
    col_order_classes(m);
}
```

В чем идея?

Например в данной реализации нельзя задать нулевую ширину для экранов начинающихся с определенного значения и выше, а надо задавать для всех

**Comment by verybigman** [comment]
Логика такова, потому что нулевая ширина скорее исключение. Ты задаешь ширину снизу вверх и для определенных ширин отключаешь.

**Comment by 4ok** [comment]
К примеру, тебе нужно отображать блок только на xlw, получается тебе нужно задать отключение блока на всех ширинах, которые находятся ниже, т.е на sw, mw, lw.

**Comment by verybigman** [comment]
Да, сейчас сделано так. Есть аргументы, почему это плохо? :)
Вт, 14 апр. 2015 г. в 22:13, 4ok <notifications@github.com>:

**Comment by 4ok** [comment]
Куда проще задать для определенного размера и выше, чем перечислять их все. Может проще сделать тогда отдельные модификаторы, одни будут отвечать только за определенную ширину, а остальные для текущей ширины и выше.

Если не разделять модификаторы, то логичнее мне кажется все же этот вариант:

```css
@media $medium {
    col_base_classes(m);
    col_visibility_classes(m);
    col_order_classes(m);
}
```

А логика изначально была взята с какого грида?

**Comment by verybigman** [comment]
Логика была взяты из опыта. Веротяно стоит подумать над вот этим:
> Может проще сделать тогда отдельные модификаторы, одни будут отвечать только за определенную ширину, а остальные для текущей ширины и выше.

**Comment by 4ok** [comment]
А нулевой офсет будет помещен сюда col_visibility_classes? https://github.com/bem-incubator/bem-grid/issues/83

**Comment by verybigman** [comment]
Думаю да)
