### ISSUE TITLE
Модификаторы сеток

### ISSUE THREAD

**Issue by AndreyGladkov** [bem-incubator/bem-grid#87]
У меня вопрос по модификаторам, я не смотрел код реализации сетки.
Но столкнулся с проблемой что при добавлении модификаторов к row они добавляются только с помощью mix: [{block: 'row_sac'}], судя по именованию классов на странице примера модификатор sac не имеет значения, поэтому и подключается как микс. На мой взгляд это не верно. Может я не верно что либо понял?

**Comment by tadatuta** [comment]
было бы правильнее `mix: { block: 'row', mods: { sac: true } }`

**Comment by AndreyGladkov** [comment]
Сегодня проверю на работе, я думал что получиться row_sac_true. 
tadatuta спасибо тебе, ты второй раз уже выручаешь:)
